version: '3.7'
services:
  web1:
    image: nixon315/web1:1.0
    environment:
      VIRTUAL_HOST: antonio-paya.test
    restart: always
    ports: 
      - 8120:80
    volumes:
      - ./web1:/usr/share/nginx/html

  web2:
    image: nixon315/web2:1.0
    environment:
      VIRTUAL_HOST:  network-soluciones.test
    restart: always
    ports: 
      - 8121:80
    volumes:
      - ./web1:/usr/share/nginx/html

  web3:
    image: nixon315/web3:1.0
    environment:
      VIRTUAL_HOST:  example-page.test
    restart: always
    ports: 
      - 8122:80
    
  web4:
    image: nixon315/web4:1.0
    environment:
      VIRTUAL_HOST:  pos.test
    restart: always
    ports: 
      - 8123:80
    depends_on: 
      - db

  web6:
    image: nixon315/web6:1.0
    environment:
      VIRTUAL_HOST:  short.test
    restart: always
    ports: 
      - "5000:5000"
    depends_on: 
      - dbacortador
  
  db:
    image: nixon315/sysfacturation:1.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3307"
    environment:
      MYSQL_USER: devdb
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: facturacion
      MYSQL_DATABASE_HOST: db
      MYSQL_PASSWORD: 12345678

  dbacortador:
    image: nixon315/bdacortador:1.0
    container_name: dbacortador
    restart: "always"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3307"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: acortador
      MYSQL_PASSWORD: 12345678

  nginx-proxy:
    image: nixon315/nginx-proxy:1.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

    restart: always
    privileged: true
